# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c9649802bb85b678dff52ee85fd55752373c7bf6e32244fb343c44584ce87f96075ea497a232a4a4d32d3468ff59302feeccd76ba941e43ff88a0ecd4c26f68

test:
  secret_key_base: 3bd6a353536b8add4e34a6579152762d01ff15bcba1a643cdb903ab42a09faf1c45e0d9e0667ff9423bc0f906ab737e3e3c765aebefef597d601f6b4c205d2ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
